---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: package facts
    package_facts:
      manager: auto
  - name: service facts
    service_facts:
  - name: assert
    ansible.builtin.assert:
      that:
        - "'haproxy' in ansible_facts.packages"
        - "'haproxy.service' in ansible_facts.services"
        - "ansible_facts.services['haproxy.service']['state'] == 'running'"
  - name: check service haproxy is running
    shell: pkill -0 haproxy
    register: hapid
    changed_when: false
    failed_when: hapid.rc != 0
  - name: check haproxy user
    shell: grep user /etc/haproxy/haproxy.cfg |awk '{print $2}'
    register: hauser
    changed_when: hauser.stdout == "admin"
    failed_when: hauser.stdout != "admin"