---
# tasks file for useradd
- name: Lookup secret from Azure Key Vault
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    tenant_id: 93f33571-550f-43cf-b09f-cd331338d086
    vault_name: LAB-MIRKO
    secret_name: sp-lab-spezie
    client_id: 56beb9c9-9669-4c5a-b881-18d57e81b214
    client_secret: M1U8Q~Hnq4t3cLUYcwLMnqB61eTRu1N643ZbbcDB
  tasks:
    - name: Get Key Vault by name
      azure_rm_keyvault_info:
        resource_group: RG-LAB
        name: "{{ vault_name }}"
      register: keyvault

    - name: Set key vault URI fact
      set_fact: keyvaulturi="{{ keyvault['keyvaults'][0]['vault_uri'] }}"

    - name: Set key vault secret fact
      set_fact: secretValue={{ lookup('azure_keyvault_secret',secret_name,vault_url=keyvaulturi, client_id=client_id, secret=client_secret, tenant_id=tenant_id) }}

    - name: Output key vault secret
      debug:
        msg: "{{ secretValue }}"