---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: instance
provisioner:
  name: ansible
  inventory:
    host_vars:
      web:
        ansible_host: 10.0.0.4
        ansible_user: azureuser
        ansible_connection: ssh
verifier:
  name: ansible
