---
# tasks file for haproxy
- name: Install haproxy
  ansible.builtin.package:
    name: haproxy
    state: present
  become: true

- name: debug variable
  ansible.builtin.debug:
    var: remote_install_path
- name: Add haproxy.cfg
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: '{{ remote_install_path }}/haproxy.cfg'

- name: Change default user
  ansible.builtin.replace:
    path: '/etc/haproxy/haproxy.cfg'
    regexp: '(\s+)user(\s+)haproxy'
    replace: '\1user dxc-admin\2'
  become: true