---
# tasks file for haproxy
- name: Install haproxy
  ansible.builtin.package:
    name: haproxy
    state: present
  become: true

- name: debug variable
  ansible.builtin.debug:
    var:
      - services_fe
- name: Add haproxy.cfg
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: '{{ remote_install_path }}/haproxy.cfg'
    owner: root
    mode: '0644'
  become: true
